version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Say Hello
          command: echo "Hello, CircleCI!"

workflows:
  version: 2
  hello-workflow:
    jobs:
      - say-hello