version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Base Ubuntu image (22.04 compatible)
    steps:
      - checkout

      - run:
          name: Install Tools
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              gcc-arm-none-eabi binutils-arm-none-eabi \
              libstdc++-arm-none-eabi-newlib cmake ninja-build make stlink-tools

      - run:
          name: Configure CMake
          command: cmake -B build -G Ninja .

      - run:
          name: Build Firmware
          command: cmake --build build --parallel

      - persist_to_workspace:
          root: .
          paths:
            - CM4/build/WheelBaseSensorSystem_CM4.elf
            - CM7/build/WheelBaseSensorSystem_CM7.elf

workflows:
  version: 2
  build-on-commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - feature/github-actions