version: 2.1
executors:
  stm32-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build-stm32:
    executor: stm32-executor
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              gcc-arm-none-eabi binutils-arm-none-eabi \
              libstdc++-arm-none-eabi-newlib cmake ninja-build make stlink-tools
      - run:
          name: Update CMake
          command: |
            sudo apt-get remove cmake
            sudo apt-get install -y wget
            wget https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-Linux-x86_64.sh
            sudo sh cmake-3.24.0-Linux-x86_64.sh --skip-license --prefix=/usr/local
      - run:
          name: Configure CMake
          command: cmake -B build -G Ninja .
      - run:
          name: Build
          command: cmake --build build --parallel
      - store_artifacts:
          path: CM4/build/WheelBaseSensorSystem_CM4.elf
          destination: firmware-binaries/CM4/WheelBaseSensorSystem_CM4.elf
      - store_artifacts:
          path: CM7/build/WheelBaseSensorSystem_CM7.elf
          destination: firmware-binaries/CM7/WheelBaseSensorSystem_CM7.elf
workflows:
  version: 2
  build_firmware:
    jobs:
      - build-stm32