name: Build STM32H7 Project

on:
  push:
    branches: ["main", "feature/github-actions"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install arm gcc toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommendations \
            gcc-arm-none-eabi cmake ninja-build

      - name: Configure Cmake
        run: cmake -B build -G Ninja .

      - name: Build
        run: cmake --build build --parallel 

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            build/CM4/WheelBaseSensorSystem_CM4.elf
            build/CM7/WheelBaseSensorSystem_CM7.elf



